### ISSUE TITLE
Training for my own dataset

### ISSUE THREAD

**Issue by Cancanneed666** [xiaofang007/CTO#2]
Hi, i am a rookie in Medseg and i wanna train my own 2d-dataset with CTO.What should i do.Or rather, which part of the code should I start by modifying.

**Comment by xiaofang007** [comment]
Hi, I would suggest to follow data_prepare.py in MedISeg framework to stack your own data and label to numpy file and then I think you can directly train with CTO. In case you do not use our preprocessing method, I would suggest to first modify dataloading/data preprocessing part of the code since during training, validation and inference, the data is loaded in numpy or tensor format whatever your initial files are.

**Comment by Cancanneed666** [comment]
Sincerely thanks for your reply and i will try this method.
